table Sales
	lineageTag: c4bbe5f1-9d55-4994-898f-d73b8da34b12

	measure 'Total Revenue' = SUM(Sales[Revenue])
		formatString: $#,0.00

	measure 'Gross Profit' = [Total Revenue] - SUM(Sales[Cost])
		formatString: $#,0.00

	measure 'Gross Margin %' = DIVIDE([Gross Profit], [Total Revenue])
		formatString: 0.0%

	measure 'Units Sold' = SUM(Sales[Units])
		formatString: #,0

	measure Orders = DISTINCTCOUNT(Sales[OrderID])
		formatString: #,0

	measure 'Average Order Value' = DIVIDE([Total Revenue], [Orders])
		formatString: $#,0.00

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: OrderDate

	column OrderID
		dataType: string
		summarizeBy: none
		sourceColumn: OrderID

	column Region
		dataType: string
		summarizeBy: none
		sourceColumn: Region

	column Salesperson
		dataType: string
		summarizeBy: none
		sourceColumn: Salesperson

	column Category
		dataType: string
		summarizeBy: none
		sourceColumn: Category

	column Product
		dataType: string
		summarizeBy: none
		sourceColumn: Product

	column Units
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Units

	column Revenue
		dataType: double
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Revenue

	column Cost
		dataType: double
		formatString: $#,0.00
		summarizeBy: sum
		sourceColumn: Cost

	column 'Month Start' = DATE(YEAR(Sales[OrderDate]), MONTH(Sales[OrderDate]), 1)
		dataType: dateTime
		formatString: MMM yyyy
		summarizeBy: none

	partition Sales = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("C:/Users/datas/Downloads/SalesDashboard-PBIP/SalesDashboard/data/sales.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"OrderDate", type date},
					{"OrderID", type text},
					{"Region", type text},
					{"Salesperson", type text},
					{"Category", type text},
					{"Product", type text},
					{"Units", Int64.Type},
					{"Revenue", type number},
					{"Cost", type number}
				})
			in
				ChangedTypes

	annotation PBI_NavigationStepName = Navigation
	annotation PBI_ResultType = Table
